language: go
go:
 - 1.6.2
 - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_script:
  - go vet ./...

before_install:
  - sudo apt-get install libgeos-dev

install:
  - go get github.com/stretchr/testify/assert
  - go get ./...

script: make test
