language: go
go:
 - 1.6.2
 - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_script:
  - go get ./...

before_install:
  - go get -u github.com/golang/lint/golint

install:
  - go get github.com/stretchr/testify/assert
  - go get ./...

script: 
  - $GOPATH/bin/golint ./...
  - make test
