[database]
  connection_string = "host=localhost user=postgres dbname=testdb sslmode=disable"
  geometry_table = "maps.maps_objects"
  geometry_column = "the_geom"
  instance_name = "postgres"

[http]
  port = "9081"

[styles]
  directory = "/path/to/styles/styles"
  watch = true
  watch_timeout = 10000

[logging]
  directory = "/path/to/logs"

